### ISSUE TITLE
555307D7 - Splinter Cell Double Agent

### ISSUE THREAD

**Issue by ttenor12** [xenia-canary/game-compatibility#172]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-canary/xenia-canary/wiki/FAQ).
- [X] The Xenia build used is from a canary branch. (not MLBS/AlexVS/master/pull requests, etc)
- [X] This issue isn't for help (tech support) with Xenia, or a game.
- [X] I've checked if this game doesn't already have a compatibility report.

### Xbox 360 Marketplace link

https://marketplace.xbox.com/en-US/Product/Splinter-Cell-Double-Agent/66acd000-77fe-1000-9115-d802555308dd

### Xenia version

https://github.com/xenia-canary/xenia-canary/commit/d61c215bd013de274dfecf3e705538bc6f8ec7e9/

### Issues

Running the emulator at default settings.

When the game is launched from default.xex:
Ubisoft logo flickers on intro cutscene
Intro menu displayed properly
The game will let you go into the multiplayer mode and create a System Link match, as well as play by yourself.
The "Bonus Features" both work properly.
It will crash after selecting "Single Player"

When the game is launched from SC4_Offline.xex:
Menu will load properly, although it flickers.
The game will crash after trying to start a new game, load a mission or load a training course.

It seems like loading screens kill the game.

### Log

[xenia.log.zip](https://github.com/xenia-canary/game-compatibility/files/12206405/xenia.log.zip)

### Screenshots

Main menu from default.xex:
![image](https://github.com/xenia-canary/game-compatibility/assets/83897177/61136e49-f05a-4add-b434-1c56a60a36bc)

Main menu from SC4_Offline.xex:
![image](https://github.com/xenia-canary/game-compatibility/assets/83897177/209c4225-df79-4856-99dd-9f81f974a52a)

### Labels

state-menus tech-engine-unrealengine

**Comment by ttenor12** [comment]
Goes in-game and is playable in the experimental XMA-Decoder build from **11/17/2023**
![image](https://github.com/xenia-canary/game-compatibility/assets/83897177/04bba988-0fce-4c55-9570-eb8a0711530b)

There are minor visual bugs such as lasers not being visible, they are supposed to come from where circled:
![image](https://github.com/xenia-canary/game-compatibility/assets/83897177/143acce4-0052-4450-aaf3-00cdc37f3951)

Overall, the game is playable from start to finish with that build. However, when testing the latest build from **1/10/2024**, the game **has no voices and crashes at the beginning of the game** prior to jumping off the Osprey, indicating a regression:
![image](https://github.com/xenia-canary/game-compatibility/assets/83897177/937590e3-d53a-4072-bbc7-bd74de2487f7)

Log of the crash from the latest 1/10/2024 build:
[xenia.log](https://github.com/xenia-canary/game-compatibility/files/13907072/xenia.log)

**Comment by Sowa95** [comment]
- requires `use_dedicated_xma_thread = false` and `use_new_decoder = true` to fix audio related crashes.
- upgrading night vision googles causes an [issue](https://github.com/xenia-canary/game-patches/issues/272).

Switching to SC4_Offline.xex and loading to missions is handled by launch_data.
Previously this game required `protect_zero = false`, but seems like it's not the case anymore.

gpu-drawing-corrupt | kernel-xex-switching | state-gameplay/playable pick what you think is right, it was reported as playable from start to finish by a few people.

**Comment by OneShot95** [comment]
The laser issue is still present stopping me from passing JBA HQ. Other levels that do not require passing lasers are fully playable.

No issues with audio when enabling the XMA decoder.

**Comment by Mich9366** [comment]
are there any solutions to play the game at a resolution higher than the native one??
on 4k monitors the native 720p looks very bad

**Comment by djbazzzofia-sketch** [comment]
No se que esté haciendo mal, pero después de una actualización reciente ya no es posible seguir jugando

**Comment by TGP482** [comment]
Xenia Edge was updated yesterday to fix the issue with the screen flickering when upscaling, so now it's properly playable at higher resolutions.

**Comment by TGP482** [comment]
### All of the issues I could find with this game as of the latest version. These are all relatively minor and don’t impact progression, if these are fixed then the game will basically be perfect. Overall, the game is very stable and hasn’t crashed a single time for me either.

### Shadows behind Sam and meshes don't render properly (this happens on all resolutions but becomes more noticeable as you increase the resolution scale)
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/9a4f41d5-b465-478a-b054-e1d5bdac5807" />

### Music occasionally cuts off after a certain point
https://github.com/user-attachments/assets/a2207743-44b7-452b-a0c4-e46162c28382
### Snow doesn't fall on Okhotsk Part 2
https://github.com/user-attachments/assets/3a89d86a-8a42-459b-aca7-e545143ee28f
### Various meshes across the game flicker
https://github.com/user-attachments/assets/d0abc1d4-3a7f-49e5-acb1-6a1a86d1c86d
### The ocean texture on Cozumel is flickery
https://github.com/user-attachments/assets/6e54cc09-79c4-4c08-94a0-9c9d910350fa
### Mirrors have a pixel offset issue on the left side of the screen
<img width="2904" height="1592" alt="Image" src="https://github.com/user-attachments/assets/2c8e7c26-23f6-443f-aef7-b5281306162e" />

### In addition the the JBA training course, the wallmine lasers for this section in Kinshasa don't render either (meeting room is fine)
https://github.com/user-attachments/assets/f9737a83-1da3-4480-ac7e-0e4b25605846

**Comment by fog13k** [comment]
Hi TGP482 thanks for the informations, glad this game is finally reaching so decency, do you know if mission selection works or this is only handled by launch_data ?

**Comment by TGP482** [comment]
Mission selection has no issues

**Comment by OneShot95** [comment]
> ### All of the issues I could find with this game as of the latest version. These are all relatively minor and don’t impact progression, if these are fixed then the game will basically be perfect. Overall, the game is very stable and hasn’t crashed a single time for me either.
> 
> ### Shadows behind Sam and meshes don't render properly (this happens on all resolutions but becomes more noticeable as you increase the resolution scale)
> <img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/9a4f41d5-b465-478a-b054-e1d5bdac5807" />
> 
> ### Music occasionally cuts off after a certain point
> https://github.com/user-attachments/assets/a2207743-44b7-452b-a0c4-e46162c28382
> ### Snow doesn't fall on Okhotsk Part 2
> https://github.com/user-attachments/assets/3a89d86a-8a42-459b-aca7-e545143ee28f
> ### Various meshes across the game flicker
> https://github.com/user-attachments/assets/d0abc1d4-3a7f-49e5-acb1-6a1a86d1c86d
> ### The ocean texture on Cozumel is flickery
> https://github.com/user-attachments/assets/6e54cc09-79c4-4c08-94a0-9c9d910350fa
> ### Mirrors have a pixel offset issue on the left side of the screen
> <img width="2904" height="1592" alt="Image" src="https://github.com/user-attachments/assets/2c8e7c26-23f6-443f-aef7-b5281306162e" />
> 
> ### In addition the the JBA training course, the wallmine lasers for this section in Kinshasa don't render either (meeting room is fine)
> https://github.com/user-attachments/assets/f9737a83-1da3-4480-ac7e-0e4b25605846

The biggest issue here for me is the lasers not rendering in the training part of JBA, this had me manually saving and reloading, causing some frustration. The other issues are so minor that once I got past JBA training, it felt smooth sailing. Some fps drops in Kinshasa.

**Comment by TGP482** [comment]
The JBA laser bug was fixed on the 13th on Xenia Edge so just download the latest build:

<img width="3575" height="1664" alt="Image" src="https://github.com/user-attachments/assets/41c97931-e860-4a83-a54d-f0abe6dac7cd" />

**Comment by kortul** [comment]
![Image](https://github.com/user-attachments/assets/fcb2edac-3f58-4157-a99b-bb43b57fc286)
🎮 **Xenia Compatibility Report:** Tom Clancy's Splinter Cell: Double Agent
**State:** ✅ Fully Playable!

**🎉 Highlights:**
✅ Completed single-player campaign on Hard with all collectibles and achievements + Secret Best Ending Epilogue Mission + 2 optional Training Missions + some coop missions (🧩 played with Title Update applied on Xenia Edge)
✅ Lasers are fixed and appear on all levels properly!
🖥️ Resolution scale 2x (1440p) with smooth performance
🎮 Multiplayer/Co-op missions fully playable as well! (can be played solo and feature unique gameplay and maps)

Note: Xbox 360 version is the most technically complete – PC and PS3 versions suffer from performance, AI and visual reductions.

🖥️ **Graphical Quirks:**
📝 Minor graphical issues reported above on January 20th still present. They are indeed very minor, except the static snow during Mission 4 – that one could be annoying.
Exceptions:
✅ Lasers on all levels now appear properly!
✅ Flickering on meshes and ocean appeared very rarely in my experience: only on a few levels, just some small objects might do it and only at certain camera angles.

⚡ **Edge vs. Canary:**
Completed on Edge version d379c156e from February 17 2026 (later versions had significant regression (crashes, audio isues))

 Performance Comparison on Mission 1:
- Xenia Edge - significantly better FPS over Canary (both tested with optimized preset, resolution x2)
->RTX 4090: Locked 30 on Edge; on Canary occasional 1-2 FPS drop
->Laptop RTX 4060: Locked 30 on Edge; on Canary drops to 22-23 FPS
->Canary crashes when exiting Single Player menu to select Multiplayer/COOP (not playable on Canary). Also can't enter Extras menu (credits + R6 Vegas trailer) - no such issue on Edge
💾 Note: Even if a crash would occur, the game offers a very generous save‑state‑like system, so progression loss in case you encounter issues is minimal to non‑existent.

**Screenshots:**
![Image](https://github.com/user-attachments/assets/04056b42-777e-4287-8d7d-6af67401786e)
![Image](https://github.com/user-attachments/assets/f4b3c040-c9ef-4b66-846f-9a5fc5df36ed)
![Image](https://github.com/user-attachments/assets/84d8f26f-3a0d-4186-99d6-808eb30caacc)
![Image](https://github.com/user-attachments/assets/2bfcd2ea-794f-4de2-adb1-fd5488674ad5)
![Image](https://github.com/user-attachments/assets/bfa89103-df19-4318-90d2-13c27c71bc22)
![Image](https://github.com/user-attachments/assets/bc6a72b5-04ae-4683-9561-4ee548fe22de)
![Image](https://github.com/user-attachments/assets/8bfe8f80-17b0-4081-b26f-0ad6b0c4742e)
![Image](https://github.com/user-attachments/assets/399ef02c-ef93-4d39-a8ff-3ec4438484b3)
![Image](https://github.com/user-attachments/assets/31ed5e03-509e-472e-bfae-f8278678c503)
![Image](https://github.com/user-attachments/assets/be00449e-5255-4412-872e-eeba666eebb7)

**Comment by ttenor12** [comment]
> ![Image](https://github.com/user-attachments/assets/fcb2edac-3f58-4157-a99b-bb43b57fc286) 🎮 **Xenia Compatibility Report:** Tom Clancy's Splinter Cell: Double Agent **State:** ✅ Fully Playable!
> 
> **🎉 Highlights:** ✅ Completed single-player campaign on Hard with all collectibles and achievements + Secret Best Ending Epilogue Mission + 2 optional Training Missions + some coop missions (🧩 played with Title Update applied on Xenia Edge) 🖥️ Resolution scale 2x (1440p) with smooth performance 🎮 Multiplayer/Co-op missions fully playable as well! (can be played solo and feature unique gameplay and maps)
> 
> Note: Xbox 360 version is the most technically complete – PC and PS3 versions suffer from performance, AI and visual reductions.
> 
> 🖥️ **Graphical Quirks:** 📝 Minor graphical issues reported on Jan 4th still present. They are indeed very minor, except the static snow during Mission 4 – that one could be annoying. Exceptions: ✅ Lasers on all levels now appear properly! ✅ Flickering on meshes and ocean appears very rarely now, only on some levels and at certain camera angles
> 
> ⚡ **Edge vs. Canary:** Completed on Edge version d379c156e from February 17 2026 (later versions had significant regression (crashes, audio isues))
> 
> Performance Comparison on Mission 1:
> 
>     * Xenia Edge - significantly better FPS over Canary (both tested with optimized preset, resolution x2)
>       ->RTX 4090: Locked 30 on Edge; on Canary occasional 1-2 FPS drop
>       ->Laptop RTX 4060: Locked 30 on Edge; on Canary drops to 22-23 FPS
>       ->Canary crashes when exiting Single Player menu to select Multiplayer/COOP (not playable on Canary). Also can't enter Extras menu (credits + R6 Vegas trailer) - no such issue on Edge
> 
> 
> **Screenshots:** ![Image](https://github.com/user-attachments/assets/04056b42-777e-4287-8d7d-6af67401786e) ![Image](https://github.com/user-attachments/assets/f4b3c040-c9ef-4b66-846f-9a5fc5df36ed) ![Image](https://github.com/user-attachments/assets/84d8f26f-3a0d-4186-99d6-808eb30caacc) ![Image](https://github.com/user-attachments/assets/2bfcd2ea-794f-4de2-adb1-fd5488674ad5) ![Image](https://github.com/user-attachments/assets/bfa89103-df19-4318-90d2-13c27c71bc22) ![Image](https://github.com/user-attachments/assets/bc6a72b5-04ae-4683-9561-4ee548fe22de) ![Image](https://github.com/user-attachments/assets/8bfe8f80-17b0-4081-b26f-0ad6b0c4742e) ![Image](https://github.com/user-attachments/assets/399ef02c-ef93-4d39-a8ff-3ec4438484b3) ![Image](https://github.com/user-attachments/assets/31ed5e03-509e-472e-bfae-f8278678c503) ![Image](https://github.com/user-attachments/assets/be00449e-5255-4412-872e-eeba666eebb7)

Are the lasers in the JBA HQ Mission 1 and Kinshasa already visible or does that issue still exist in the Xenia Edge version you tried?

**Comment by ttenor12** [comment]
My bad, I closed this by mistake.

**Comment by Finoderi** [comment]
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/6259d80d-31bb-4b23-a448-39e79a11a686" />
Lasers are visible on the recent build canary_experimental@3b8debc from 12.03.2026.

**Comment by Finoderi** [comment]
> ->Canary crashes when exiting Single Player menu to select Multiplayer/COOP (not playable on Canary). Also can't enter Extras menu (credits + R6 Vegas trailer) - no such issue on Edge

That happens only if you start the game from SC4_Offline.xex instead of default.xex. It's kinda in the name...
Coop missions are available on xenia-canary as well.
