### ISSUE TITLE
454107E9 - The Godfather

### ISSUE THREAD

**Issue by Sowa95** [xenia-canary/game-compatibility#256]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-canary/xenia-canary/wiki/FAQ).
- [X] The Xenia build used is from a Canary branch. (not UWP/MLBS/AlexVS/master/pull requests, etc)
- [X] This issue isn't for help (tech support) with Xenia, or a game.
- [X] I've checked if this game doesn't already have a compatibility report.

### Xbox 360 Marketplace link (optional)

http://marketplace.xbox.com/en-US/Product/The-Godfather/66acd000-77fe-1000-9115-d802454107e9

### Xenia Canary version

https://github.com/xenia-canary/xenia-canary/commit/ea762e9f1b173f6f9e4f33d5b30e22f2fb8a79b1

### Issues

- saving fixed in [1688ea5](https://github.com/xenia-canary/xenia-canary/commit/1688ea5d6909621e9871b90097a10e71994e3ad6).
- slow audio fixed in [8f5da61](https://github.com/xenia-canary/xenia-canary/commit/8f5da619f99fc66adc01c060b6b491939abae9d0). Minor audio crackles/corruption still present.
- audio in vehicles is completely broken, if triggered it leads to issues in cutscenes and softlocks on loading screens.

### Log

[xenia.zip](https://github.com/user-attachments/files/17361623/xenia.zip)

### Screenshots

![1](https://github.com/user-attachments/assets/d4289d58-a5fb-4770-bf5f-d007ff524923)

### Labels

apu-garbage | state-gameplay | tech-engine-renderware

**Comment by Gliniak** [comment]
Update: Savefiles fixed in https://github.com/xenia-canary/xenia-canary/commit/1688ea5d6909621e9871b90097a10e71994e3ad6
To make savefile from console compatible you need to open header file and add space at the end of phrase "The Godfather" near the end of a file. (aka: "The Godfather" to "The Godfather ")

Note about savefiles.

There is one issue, but it exists in two different locations.
1. Package name on console is called: "The Godfather " and that name is taken by: XCONTENT_DATA file_name_raw field. Problem is that console accepts filenames with trailing spaces meanwhile windows automatically removes them. This will be problematic even after implementing STFS writer.
2. Internal filename is also called "The Godfather " which currently causes issues for the same reason as described in point 1.

Address for EU version: 82A6CD68
It's strncmp which fails, due to that space at the end.

**Comment by Elzama** [comment]
Audio issue persists with The Godfather game.

Something broke the audio after releasing [a25ea03](https://github.com/xenia-canary/xenia-canary/releases/tag/a25ea03)
Before it, with [78ff40a](https://github.com/xenia-canary/xenia-canary/releases/tag/78ff40a), the sound works fine, but it cannot save the game.

Here is the comparison on both releases:
https://github.com/xenia-canary/xenia-canary/compare/78ff40a...a25ea03?diff=split&w#diff-59fb0d9dd21d6dd3662e593d08525ff780e7ee89a98abffd51dd2f7ebe07a2a7

**Comment by JayCapicolla** [comment]
I have no idea what's causing infinite loading screens during the training mission where luca brasi dies which is like the fourth training mission, but i am on Xenia Canary ver. 3b8debc (which was updated a few days ago around march 8th or 9th 2026), on Win11, and am running the NA Godfather version 454107E9 

I'm still new to pc emulation and have no idea what else i can provide to help for future users to reference other than what i have given. Also i can confirm audio issues still persist with vehicles. 

i have tried to run different audio versions through the recommendations of reddit through the Xenia Manager for the car audio but none seem to alleviate the continuous beep heard after two seconds of entering a vehicle and accelerating. 

To alleviate the infinite loading screens i have tried methods recommended on reddit by running in windowed mode, lowering resolution while in windowed mode, lowering fps to the normal 30fps release, set the mrt_edram_used_range_clamp_to_min value to false (normally set to true), set the d3d12_tessellation_wireframe value to true (normally set to false) as recommended for RDR1 fix. it was also recommend to let shaders compile for at least 5mins before giving up. tried that and didnt make a change. based off what ive read it appears it may be Win11 as "older games struggle to run on newer Windows versions". Dont have a lot of time so when i can i will learn to change Windows versions for the game and see if that works and report back.

UPDATE:
Tried changing windows version from win11 to win7 with admin permission to not avail. Converted the iso into xex to see if that would fix the infinite loading screens. Nope. At this point i believe it to be purely how the game functions currently under emulation and may not be fixed anytime soon, if at all for this particular game. As of 3/23/26 i would only play this game with the expectation that you cannot complete the story but the general gameplay (minus car audio issues) is fine and playable.

**Comment by JayCapicolla** [comment]
> I have no idea what's causing infinite loading screens during the training mission where luca brasi dies which is like the fourth training mission, but i am on Xenia Canary ver. 3b8debc (which was updated a few days ago around march 8th or 9th 2026), on Win11, and am running the NA Godfather version 454107E9
> 
> I'm still new to pc emulation and have no idea what else i can provide to help for future users to reference other than what i have given. Also i can confirm audio issues still persist with vehicles.
> 
> i have tried to run different audio versions through the recommendations of reddit through the Xenia Manager for the car audio but none seem to alleviate the continuous beep heard after two seconds of entering a vehicle and accelerating.
> To alleviate the infinite loading screens i have tried methods recommended on reddit by running in windowed mode, lowering resolution while in windowed mode, lowering fps to the normal 30fps release, set the mrt_edram_used_range_clamp_to_min value to false (normally set to true), set the d3d12_tessellation_wireframe value to true (normally set to false) as recommended for RDR1 fix. it was also recommend to let shaders compile for at least 5mins before giving up. tried that and didnt make a change. based off what ive read it appears it may be Win11 as "older games struggle to run on newer Windows versions". Dont have a lot of time so when i can i will learn to change Windows versions for the game and see if that works and report back.

UPDATE:
Tried changing windows version from win11 to win7 with admin permission to not avail. Converted the iso into xex to see if that would fix the infinite loading screens. Nope. At this point i believe it to be purely how the game functions currently under emulation and may not be fixed anytime soon, if at all for this particular game. As of 3/23/26 i would only play this game with the expectation that you cannot complete the story but the general gameplay (minus car audio issues) is fine and playable.

**Comment by has207** [comment]
audio in vehicles still broken

**Comment by Cal-Woods** [comment]
running into audio in vehicle glitch and I definitely have the latest version as I just downloaded it today.

really hope this is still being actively looked into as I quite enjoyed this game and I have just recently got back into emulation. 

lots of love for this game

**Comment by nfxw** [comment]
Tested on canary 888b9ad and with new decoder audio in cars almost fixed, but there is still crackling sounds.

https://github.com/user-attachments/assets/231d5d20-b3fb-4696-a566-b9cd254a93d7

**Comment by Kalashnikov1947** [comment]
Current version of Xenia Canary (aee0871) now refuses to apply the title update for the game (at least for the European copy I'm using) by default. Need to set "allow_incompatible_title_update" to "true".

<img width="1288" height="770" alt="Image" src="https://github.com/user-attachments/assets/a5fa6aa6-dc6d-4545-ba3f-03d09776fe97" />
