### ISSUE TITLE
454107D9 - Need for Speed Most Wanted (2005)

### ISSUE THREAD

**Issue by 1HackJack1** [xenia-canary/game-compatibility#28]
[Marketplace](https://en.wikipedia.org/wiki/Need_for_Speed:_Most_Wanted_(2005_video_game) )

Tested on https://github.com/xenia-canary/xenia-canary/commit/293e9582ec35d30ef17a25f08858a82eed945f69

# Issues:
Menu and intro - works good. The game have some problems with corrupt drawing, and big problems with 'light". There are no music and sounds in the menu (Only in the intro is). Impossible to create profile at start game, only in menu.  After choosing a "New Career", emulator "freezes" - nothing happens.

# Log:
[xenia.zip](https://github.com/xenia-canary/game-compatibility/files/4199093/xenia.zip)

# Screenshot(s):
![XeniaCanary_NFSMW2005_13_02_2020](https://user-images.githubusercontent.com/60978912/74449299-0fbec980-4e85-11ea-96f1-b6a668164498.png)

![XeniaCanary_NFSMW2005_13_02_2020_2](https://user-images.githubusercontent.com/60978912/74449313-14837d80-4e85-11ea-9a3d-991bed9378f5.png)

![XeniaCanary_NFSMW2005_13_02_2020_3](https://user-images.githubusercontent.com/60978912/74449330-18af9b00-4e85-11ea-8089-2d2d49839b64.png)

![XeniaCanary_NFSMW2005_13_02_2020_4](https://user-images.githubusercontent.com/60978912/74449337-1baa8b80-4e85-11ea-97fc-ab870f8c1a50.png)

![XeniaCanary_NFSMW2005_13_02_2020_5](https://user-images.githubusercontent.com/60978912/74449350-1f3e1280-4e85-11ea-964e-d3db13076db7.png)

# Labels:
cpu-timing, cpu-jit-problems, gpu-corrupt-drawing, state-gameplay

**Comment by TorutheRedFox** [comment]
Note: the game doesn't actually use EAGL aside from a small handful of helper stuff borrowed from it, so I'm not sure the EAGL tag really applies (it uses a custom engine)

**Comment by chicodr** [comment]
So i have mssing audio, overlighting and a little performance issues. I need help and can#t really follow this thread here.

**Comment by TorutheRedFox** [comment]
> So i have mssing audio, overlighting and a little performance issues. I need help and can#t really follow this thread here.

brightness issues are solved by enabling d3d12_readback_resolve

**Comment by chicodr** [comment]
> brightness issues are solved by enabling d3d12_readback_resolve
In Xenia settings?

What about sound?

**Comment by TorutheRedFox** [comment]
in xenia settings yes

sound is still broken sadly

**Comment by chicodr** [comment]
> > So i have mssing audio, overlighting and a little performance issues. I need help and can#t really follow this thread here.
> 
> brightness issues are solved by enabling d3d12_readback_resolve

nope, still super bright

**Comment by IamRamen-R** [comment]
i am having the same issues as well, the sound and the brightness is really high. at the beggining its all fine until the menu when you boot up the career the sound stops, even in the cutscenes

**Comment by CooleyZ801** [comment]
Game runs fine and seems to have no graphical issues, but still has sound issues and freezes upon beating Razor in prolouge. All patches applies, have used but d3d12 and Vulkan, and tried different timescales, all to no avail

**Comment by JannisE36328i** [comment]
sadly still no fix about the brightes besides using readback which lets u play on like 30 fps

**Comment by nfxw** [comment]
Finished the game, move to playable.
To fix silent audio - use patches+new decoder.
Issues:
1. When you using patches+new decoder ui sounds goes silent.
2. If you upscale higher than 720p you experience flickerig of the roads when it's raining(only happens during the rain).

![Image](https://github.com/user-attachments/assets/51659c73-65b9-49f4-81f1-d600de46283e)
![Image](https://github.com/user-attachments/assets/64649eee-44e1-4706-a6b6-73cccc219370)
![Image](https://github.com/user-attachments/assets/64e645d1-f6cd-4bd4-9a62-427358c0976b)
![Image](https://github.com/user-attachments/assets/d735337f-12a7-4fa0-af87-5b0473b31aa3)

**Comment by Monkeygamer2010** [comment]
Shouldn’t this still be listed as state-gampeplay? I wouldn’t say it’s really playable  if the audio isn’t working correctly and patches need to be used to get rid of post processing issues

**Comment by TTVohhitscodie** [comment]
still isn't working, fixed the lighting issue with the readback resolve, still no audio. loading game in vulkan still freezing after selecting career, loading in d3d12 fixes that issue but then always freezes when almost at the finish line of the first race.

**Comment by nfxw** [comment]
> still isn't working, fixed the lighting issue with the readback resolve, still no audio. loading game in vulkan still freezing after selecting career, loading in d3d12 fixes that issue but then always freezes when almost at the finish line of the first race.

Use patches and new decoder.

**Comment by t0ffif33** [comment]
> > still isn't working, fixed the lighting issue with the readback resolve, still no audio. loading game in vulkan still freezing after selecting career, loading in d3d12 fixes that issue but then always freezes when almost at the finish line of the first race.
> 
> Use patches and new decoder.

In addition I changed use_dedicated_xma_thread = false 

Now everthing runs smooth

**Comment by paulodt3d-ops** [comment]
Still no audio for me. I'm using "use_dedicated_xma_thread = false" and "use_new_decoder = true". Latest Xenia Canary release

**Comment by nfxw** [comment]
> Still no audio for me. I'm using "use_dedicated_xma_thread = false" and "use_new_decoder = true". Latest Xenia Canary release

Try to use_dedicated_xma_thread and new decoder to true+Skip audio loop stuck code patch.
There is no audio in ui menu, but in the game the audio is still present.

**Comment by paulodt3d-ops** [comment]
> Try to use_dedicated_xma_thread and new decoder to true+Skip audio loop stuck code patch. There is no audio in ui menu, but in the game the audio is still present.

Still same thing. The game even crashes sometimes.

**Comment by nfxw** [comment]
> > Try to use_dedicated_xma_thread and new decoder to true+Skip audio loop stuck code patch. There is no audio in ui menu, but in the game the audio is still present.
> 
> Still same thing. The game even crashes sometimes.

Confirmed, the audio goes silent in both ways, probably a regression.

**Comment by whilmadicfit** [comment]
dumb question i am able to get pretty far but im stuck on the izzy races with the sound cutting off then freezing when i finish the race. i see where someone say add sound patch idk what that is can someone explain how to add the sound patch?

**Comment by nfxw** [comment]
> dumb question i am able to get pretty far but im stuck on the izzy races with the sound cutting off then freezing when i finish the race. i see where someone say add sound patch idk what that is can someone explain how to add the sound patch?

Download the zip from - https://github.com/xenia-canary/game-patches
Drop the "patches" folder into your xenia canary folder.
In patches folder find nfs most wanted and change skip audio loop stuck code to true, additionally "Disable Post Processing" to true to change over-bright image.

**Comment by whilmadicfit** [comment]
im still new to github so idk how to properly reply but thank you nfxw i was able to do the patch still had issues when i start a race the sound cuts with the patch on still testing different settings will return with hopefully good news!

**Comment by nfxw** [comment]
> im still new to github so idk how to properly reply but thank you nfxw i was able to do the patch still had issues when i start a race the sound cuts with the patch on still testing different settings will return with hopefully good news!

Just try build from may or june, played through career completely.
Right now there is regression in latest xenia canary build in this game("sound cut" issue).
https://github.com/xenia-canary/xenia-canary-releases/releases?page=3 - try [e601b5a] build or maybe even earlier build.

**Comment by whilmadicfit** [comment]
i tried 4 different builds none seemed to work with the patches including the one you mentioned. maybe itll be fixed in future builds

**Comment by paulodt3d-ops** [comment]
Same here, tested a couple of older builds, including the [e601b5a]. Same thing, audio always goes silent.

**Comment by cuttherug** [comment]
Issues still present [US Version]:

No sound during race
Game freeze at end of race

Methods used with no improvement:

Windows 11 // 3070ti // 32gb RAM
Latest Canary November (48c854f)
Patches and settings:
use_dedicated_xma_thread = true
use_new_decoder = true
skip audio loop stuck = true

**Comment by ZerbZerb** [comment]
I followed the instructions and have the English language version run fully playable with missing UI sounds and no cut audio in game anymore, with enabled patches and new decoder on true. The exact same settings with a German version still cause cut audio in game and freezes, and the UI sounds do not disappear. I tried various things but I cannot understand why the German version behaves differently compared to the English version, despite using the same set up and settings. I even swapped config files. But the German version still has UI sounds, but in game cut audio and freezes. 

Any idea how to make the German version behave like the English?

**Comment by ZerbZerb** [comment]
After some more testing, and the English version running without any freezes, I believe that the below patch is not usable for the German version of the game... It just does not work. 

The ‘disable post processing’ patch does work with the German version though. 

Can someone maybe look into tweaking the patch of ‘skip audio loop stuck code’ by author ‘Gliniak’ to also work with the German version with the following hash: 
75548947DB063F37

Maybe the patch address or values need to be different here?

**Comment by rev666** [comment]
After many tests during several hours, I found the correct way to play this game without audio cut-offs using Xenia-Edge as of December 18th 2025.

*First you need to choose the new audio decoder.

*2nd: you MUST uncheck the Dedicated Thread option for the audio.

*And 3rd and MOST IMPORTANT: do NOT skip any cutscene in the game besides the intro and the PSA before the main menu. I tested this during many hours until finding that it was the culprit of the issues many of you are having with the audio. 
Let all the custscenes play entirely. If you skip any of the cutscenes, you WILL HAVE audio cutoff issues.

About the graphics, it works just as good as the real hardware. Also, if you want more performance out of your GPU, change the internal_display_resolution from the default "8" to "0". "0" equals changing the resolution of the Xbox 360 to 640x480p, and because this game is an early title in the Xbox 360 life, changing the resolution changes the performance of the game (the FPS). It works this way both in the real hardware and the Xenia emulator, but on Xenia you will still get high resolution by changing the rendering scale (2x = 1440p and 3x = 4K).

I played like that for 6 hours and didn't have a single issue or crash the entire time.

**Comment by rev666** [comment]
here is the proof: https://www.youtube.com/watch?v=rJrd7Niyniw

**Comment by ttenor12** [comment]
> here is the proof: https://www.youtube.com/watch?v=rJrd7Niyniw

Did you enable any of the two available patches, by any chance?

**Comment by rev666** [comment]
> > here is the proof: https://www.youtube.com/watch?v=rJrd7Niyniw
> 
> Did you enable any of the two available patches, by any chance?

If you had watched the video, you would know. I show the patches menu right at the beginning of it.

**Comment by ttenor12** [comment]
> > > here is the proof: https://www.youtube.com/watch?v=rJrd7Niyniw
> > 
> > 
> > Did you enable any of the two available patches, by any chance?
> 
> If you had watched the video, you would know. I show the patches menu right at the beginning of it.

Doesn't matter. I typed this before watching the video and tried without the patches first. Still doesn't work anyway, with and without patches.

**Comment by rev666** [comment]
> > > > here is the proof: https://www.youtube.com/watch?v=rJrd7Niyniw
> > > 
> > > 
> > > Did you enable any of the two available patches, by any chance?
> > 
> > 
> > If you had watched the video, you would know. I show the patches menu right at the beginning of it.
> 
> Doesn't matter. I typed this before watching the video and tried without the patches first. Still doesn't work anyway, with and without patches.

It does matter. The video is proof. The way you handle the emulator proves something else, though.

**Comment by cuttherug** [comment]
> > > > here is the proof: https://www.youtube.com/watch?v=rJrd7Niyniw
> > > 
> > > 
> > > Did you enable any of the two available patches, by any chance?
> > 
> > 
> > If you had watched the video, you would know. I show the patches menu right at the beginning of it.
> 
> Doesn't matter. I typed this before watching the video and tried without the patches first. Still doesn't work anyway, with and without patches.

Hey Tenor, I noticed that my EU version runs better than my US version. Not sure if that will help you, or if you're already using the EU version.

**Comment by nfxw** [comment]
In xenia edge you can now play upscaled with all postprocessing.
I think that this game should be moved to playable, all effects is now restored, audio is almost fixed.

<img width="1920" height="1200" alt="Image" src="https://github.com/user-attachments/assets/d4c7af7c-f6b5-474a-8e9d-80ff79dbe44f" />

**Comment by skinnedmedalgaming-sudo** [comment]
To anyone still having issues with the usa version, the EU version works completely fine with no issues.

**Comment by DrDoink** [comment]
what about UWP build? the game runs OK, I would say performance is 1:1 to the original xbox360 but obviously we want to depart from that and at least get locked 60 at some point (I think the series X should be able to handle it). On the UWP build the game crashes when using new audio decoder and/or using SDL apu.

**Comment by DrDoink** [comment]
nevermind runs 60fps locked now. with patch that disables audio loopback and shaders

**Comment by afk1234849** [comment]
With skip audio loop stuck enabled cop siren sound will be muted

**Comment by afk1234849** [comment]
Also when disabling skip audio loop stuck, some cars would cause the game to be muted(ie Cobalt SS, RX8, Lancer Evolution), returning to safe house at this point will cause the game to freeze

**Comment by Zaccoder56** [comment]
is the random mute timing with xma on without a patch still a problem?

**Comment by nfxw** [comment]
@Zaccoder56 
Still an issue on canary c50b036 and edge 959322478.

**Comment by has207** [comment]
Forgot to mention it here before, but after latest changes in xma decoder you actually want xma_decoder=new and use_dedicated_xma_thread=true for this game for most stability, it will still drop sound from time to time but fairly playable from the small amount of testing I did.

**Comment by afk1234849** [comment]
Seems like the latest update fixed the audio issues with cars, but the audio will still be muted when a police helicopter is nearby.

**Comment by OhLookWeGOTit** [comment]
From [this build](https://github.com/xenia-canary/xenia-canary/pull/1014/files) audio issues and crashes after buying your first car and going to Mia garage and also noisy menu sfx is fixed. 
Edit: Also Speedbreaker audio issues are fixed too.

Tested both Europe & USA

<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/fc62c008-d88a-451d-897f-2d9e44950862" />

<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/cc5e3b3c-bb59-4e40-a8fd-04e9df05d0b7" />

log:

[xenia.zip](https://github.com/user-attachments/files/28151474/xenia.zip)

**Comment by nfxw** [comment]
On xenia canary e7d0e45 and xenia edge 14992e1 the game is fixed.
To fix overbright image use readback_resolve to fast and to fix audio use new decoder.
@BorealisEcho i think that the game should be in playable.
Also on canary only works full of readback_resolve and on edge both fast and full.

<img width="1920" height="1200" alt="Image" src="https://github.com/user-attachments/assets/0c67963e-812c-4f27-90b0-786ebf6d6d5c" />
<img width="1920" height="1200" alt="Image" src="https://github.com/user-attachments/assets/10548e0c-6bd8-4ed9-8e03-18a1250075c6" />
<img width="1920" height="1200" alt="Image" src="https://github.com/user-attachments/assets/beb45caf-9947-4b65-aee9-7b126a414217" />
[xenia.log](https://github.com/user-attachments/files/29159419/xenia.log)

**Comment by endervad** [comment]
As of https://github.com/xenia-canary/xenia-canary/releases/tag/6a45452 the game works with default settings. The only issue is overexposure which is fixed the following way:

### Native resolution

Just `readback_resolve = "fast"` is enough for the game to look correctly.

### Scaled resolution

I've been playing around with 2x scaling. The problem is that with only `readback_resolve = "fast"` overexposure still persists. You can set it to `"full"` to fix overexposure but performance tanks pretty hard to 20-30 FPS. Instead, this combination of settings works:
```
readback_resolve = "fast"
draw_resolution_scale_threshold = 256
draw_resolution_scale_x = 2
draw_resolution_scale_y = 2
draw_resolution_scaled_texture_offsets = true
```
Personally I've also disabled VSync. On my rig the result is around 50-60 FPS, with the lowest I've seen is 40 FPS, and the highest - 80 FPS.
The downside is that this fix **doesn't work on every boot**. Though in my experience I didn't have to restart the game more than 2 times.

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/7de1ee7f-9492-4da4-8cea-807859896013" />

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/0dbc762a-0648-4166-b75f-5096fd1d046c" />

I'd like to also mention that with `readback_resolve = "none"` (default) the game becomes GPU bound as I've been reaching up to 150 FPS at almost 100% GPU usage with 2x scaling.
