### ISSUE TITLE
4D5607D1 - Deadly premonition

### ISSUE THREAD

**Issue by LuismaSP89** [xenia-canary/game-compatibility#41]
[Marketplace](http://marketplace.xbox.com/...)

Tested on https://github.com/xenia-canary/xenia-canary/commit/660559bd372e34f62979b43fc9bf23b81f236037

# Issues:
Language selection is not working properly. I have a copy of deadly premonition which already includes multi5 languages (Spanish in my case) but for some reason, the game is all the time on english. This is the only game I got problems with the xenia's internal language selector. (Using canary and changed the values for language and country in config) all other games works as it shoud and shows in spanish.

In the other side, the game is playable with minor graphical issues.

# Log and config:

[xenia.zip](https://github.com/xenia-canary/game-compatibility/files/4567887/xenia.zip)
[xenia-canary-config.zip](https://github.com/xenia-canary/game-compatibility/files/4567888/xenia-canary-config.zip)

# Screenshot(s):

**Screenshot from "updata" folder proving that it's a Multi-5 game:**

![1](https://user-images.githubusercontent.com/12205048/80866551-9a96af80-8c8f-11ea-9344-39d955bba834.jpg)

# Labels:
(recommended labels)

**Comment by LuismaSP89** [comment]
My specs:
Windows 10 x64
i7 4790k
GTX 970
16GB DDR3

**Comment by BiwwytheBoi** [comment]
screenshots of the game?

**Comment by LuismaSP89** [comment]
@BiwwytheBoi Here you go:

![4](https://user-images.githubusercontent.com/12205048/80868028-2f9da680-8c98-11ea-905a-7d39f25593ed.jpg)
![1](https://user-images.githubusercontent.com/12205048/80868029-30ced380-8c98-11ea-95c1-25b809e1305a.jpg)
![2](https://user-images.githubusercontent.com/12205048/80868030-32000080-8c98-11ea-97c1-485afe5c8e18.jpg)
![3](https://user-images.githubusercontent.com/12205048/80868031-32989700-8c98-11ea-9367-44eb11a54f2e.jpg)

**Comment by BillieBlueberry** [comment]
was the UE workaround on?

**Comment by Forgottenshadow89** [comment]
@BiwwytheBoi Yes, it's on, but also tested with it disabled and makes no difference.

**Comment by BillieBlueberry** [comment]
just making sure

**Comment by macedonsky777** [comment]
Still no fixes for this game?

**Comment by Satumariko** [comment]
現在のxenia_edgeではグラフィックの色の不具合は改善されています。
どのバージョンで改善されたかまでは後追いできていないため、正確な改善バージョンは不明です。

The color-related graphics issues have already been fixed in the current xenia_edge builds.
I haven’t been able to trace exactly which version introduced the fix, so the precise build where it was resolved is unknown.

<img width="3840" height="2160" alt="Image" src="https://github.com/user-attachments/assets/fd29be19-9549-42bf-a532-2a729b972fda" />

<img width="3840" height="2160" alt="Image" src="https://github.com/user-attachments/assets/037f0df6-abfe-4ee6-8d67-da1c868f8909" />

<img width="3840" height="2160" alt="Image" src="https://github.com/user-attachments/assets/2b0104a3-acc4-4d65-ad75-813ec8bf2842" />

**Comment by has207** [comment]
> 現在のxenia_edgeではグラフィックの色の不具合は改善されています。 どのバージョンで改善されたかまでは後追いできていないため、正確な改善バージョンは不明です。
> 
> The color-related graphics issues have already been fixed in the current xenia_edge builds. I haven’t been able to trace exactly which version introduced the fix, so the precise build where it was resolved is unknown.

It's well known, the original commit is [6947a91e](https://github.com/has207/xenia-edge/commit/6947a91e), but there were a number of refinements over time as that change broke rendering in other games.

**Comment by Versalium** [comment]
Yes, that one was fixed but the game still has issues with shadows and other things. I'm not sure if I should even make a post on those issues here, or they're already known and it's only a matter of waiting for the fix. 

Would appreciate some advice here, I really want this game to get into playable state. If it would help, I could make screenshots from Xbox One S (backwards compatible) to be a reference for how things should look like.

**Comment by has207** [comment]
> Yes, that one was fixed but the game still has issues with shadows and other things. I'm not sure if I should even make a post on those issues here, or they're already known and it's only a matter of waiting for the fix.
> 
> Would appreciate some advice here, I really want this game to get into playable state. If it would help, I could make screenshots from Xbox One S (backwards compatible) to be a reference for how things should look like.

it should be completely playbable on latest edge build, floating shadows and sound issues have been resolved, if you're seeing problems on latest then report it ~~on the edge bug tracker~~ *in discord* not here.

**Comment by Versalium** [comment]
> it should be completely playbable on latest edge build, floating shadows and sound issues have been resolved, if you're seeing problems on latest then report it ~on the edge bug tracker~ _in discord_ not here.

What if I don't use discord, where should I report? I tested the latest Edge, the shadows are still a mess and some textures are still buggy, the environment textures are very noisy (they're noisy on a 360 as well but not as much), LODs have issues, some sounds like the car's engine sound has issues (popping, clicking).
