### ISSUE TITLE
5841125E - Joy Ride Turbo

### ISSUE THREAD

**Issue by ConLenov** [xenia-canary/game-compatibility#595]
### Validation

- [x] I've read the [FAQ](https://github.com/xenia-canary/xenia-canary/wiki/FAQ).
- [x] The Xenia build used is from a Canary branch. (not UWP/MLBS/AlexVS/master/pull requests, etc)
- [x] This issue isn't for help (tech support) with Xenia, or a game.
- [x] I've checked if this game doesn't already have a compatibility report.
- [x] Main report is done on Windows with usage of D3D12 backend

### Wiki page (optional)

https://github.com/xenia-canary/game-compatibility/wiki/...

### Xbox 360 Marketplace link (optional)

https://www.xbox.com/ru-RU/games/store/joy-ride-turbo/C1ZWH2BZ9TSF

### Xenia Canary version

https://github.com/xenia-canary/xenia-canary/commit/b864149575f267b6b8804a01e5a4f4483d63e764

### Issues

The game looks like pixel censorship. UI works without problems. My PC:

CPU: Intel i7-3770
GPU: RTX 3050
RAM: 16 Gb

### Log

[xenia.log](https://github.com/user-attachments/files/20576633/xenia.log)

### Screenshots

![Image](https://github.com/user-attachments/assets/839ce45b-7021-4a8b-9c9b-f6834b93a7ae)

![Image](https://github.com/user-attachments/assets/343459ca-d80a-4319-9250-8e1d11642a8d)

### Labels

gpu-drawing-corrupt,

**Comment by eli209980** [comment]
I have the same issue, its annoying but playable

**Comment by Margen67** [comment]
Please provide a `state-` label next time.

**Comment by ModBoyex** [comment]
I can confirm I also have the same issue

**Comment by DanielCornflake** [comment]
Graphics corruption was fixed in https://github.com/xenia-canary/xenia-canary/commit/d119505289d540f61ae3d4ba6168f1145625277a

Shader issues on car models using D3D12 was fixed in https://github.com/xenia-canary/xenia-canary/commit/da47dfaacfae1134b238af9083a7f3d413c6cbbe

Smoke effects and lens flares are pixelated.
Runs at 30fps by default, game speed is tied to fps
Missing avatar support but game still runs fine.

<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/e65bee3b-b32b-4876-8e87-113b8d369e98" />

<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/6b7eb4b3-f192-4f99-aef6-1feb0e9b2083" />

<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/33452ca8-e1e1-46cf-ab54-ca3b9d7035d8" />

**Comment by goldislead** [comment]
xenia-canary/xenia-canary@437a728 fixed the shuffled particles and glare sprites.

Both Vulkan paths still experience the rare vertex explosion that can be tempered with F5.
