### ISSUE TITLE
544307D2 - Dead or Alive Xtreme Beach Volleyball 2

### ISSUE THREAD

**Issue by YukitoNakamura** [xenia-canary/game-compatibility#619]
### Validation

- [x] I've read the [FAQ](https://github.com/xenia-canary/xenia-canary/wiki/FAQ).
- [x] The Xenia build used is from a Canary branch. (not UWP/MLBS/AlexVS/master/pull requests, etc)
- [x] This issue isn't for help (tech support) with Xenia, or a game.
- [x] I've checked if this game doesn't already have a compatibility report.
- [x] Main report is done on Windows with usage of D3D12 backend

### Xenia Canary version

https://github.com/xenia-canary/xenia-canary/commit/c5d6db2840d643ef344ab7a68e07daa9ff3c1b05

### Issues

- File IO error when going to options(image 1).
- Garbled background in the character select screen(image 2), you can see the characters, text and foreground elements.(Solved)
- Garbled screen after character select(image 3).(Solved)
- Missing textures post-char select's intro: https://github.com/xenia-canary/game-compatibility/issues/619#issuecomment-2999936117
Issues 2 and 3 are solved with `clear_memory_page_state = true`.

Overall, goes past the intro, but these three issues are the main glaring ones. 
Updates:
2025-06-24: Store items show correctly. Spotted issue with some missing textures, see above. Store models have a pristine look, though, which is good. Game is looking quite good, just have to explore more.
Strange skin colors and more missing textures.

### Log

[xenia_log.zip](https://github.com/user-attachments/files/20856593/xenia_log.zip)

### Screenshots

![Image](https://github.com/user-attachments/assets/ef1a44c4-9cf9-4662-95ec-3bc48de68d58)

![Image](https://github.com/user-attachments/assets/8e1eead5-44bb-469a-8dc9-05da48418430)

![Image](https://github.com/user-attachments/assets/9dc777d4-0ba8-4033-93af-0ae1ec16513f)

### Labels

state-intro,gpu-drawing-corrupt,

### My Hardware
Intel Xeon E5-2670v3 2.4Ghz
RTX 3060 12GB
RAM: 16GB

**Comment by A1eNaz** [comment]
does `clear_memory_page_state = true` work for the garbled graphics?

**Comment by YukitoNakamura** [comment]
> does `clear_memory_page_state = true` work for the garbled graphics?

Excuse me, but how do I enable it?

**Comment by InsomniacX2** [comment]
> > does `clear_memory_page_state = true` work for the garbled graphics?
> 
> Excuse me, but how do I enable it?

Edit your xenia-canary.config.toml file using a notepad program. I use notepad ++.

**Comment by YukitoNakamura** [comment]
Hello, yes, it does help a bit. Beach screen shows up correctly on character select. Now it's this

![Image](https://github.com/user-attachments/assets/5a740286-4395-4aab-806c-d4c7fd78351d)

And this 

![Image](https://github.com/user-attachments/assets/9c416bd7-5408-45a3-bb96-452ede0f4467)

![Image](https://github.com/user-attachments/assets/8986114a-2a5c-41c7-ac3d-dc483b32152c)

![Image](https://github.com/user-attachments/assets/bf378cc6-7ce8-4c0f-aef0-6c28c5d75f3e)

**Comment by acleet78** [comment]
Hello,

Is anyone experiencing an issue where the girls' hair get stuck in one frame of its animation? I am getting the same black texture on the ground in some areas, which I can live with, and other animations are fine, AND the F5 cache clear works when switching options in the menu or when models start to go crazy, but I can't get the hair to actually animate. When I hit F5 it updates the hair to be in whatever position it would have been had the animations been functioning, but then it just sticks that way (while also flickering) until the next time I refresh and then it updates to that specific frame of animation, on and on. I have all of my Xenia settings on default and I'm running on an NVIDIA 4060 and a Ryzen 7 7700.

Sorry if I don't have more details, I'm not a very tech savvy person, I'm not sure if there's a log I should be uploading or something.

Also setting clear_memory_page_state = true doesn't seem to change anything. I still have to hit F5 every time it goes weird.

**Comment by YukitoNakamura** [comment]
> Hello,
> 
> Is anyone experiencing an issue where the girls' hair get stuck in one frame of its animation? I am getting the same black texture on the ground in some areas, which I can live with, and other animations are fine, AND the F5 cache clear works when switching options in the menu or when models start to go crazy, but I can't get the hair to actually animate. When I hit F5 it updates the hair to be in whatever position it would have been had the animations been functioning, but then it just sticks that way (while also flickering) until the next time I refresh and then it updates to that specific frame of animation, on and on. I have all of my Xenia settings on default and I'm running on an NVIDIA 4060 and a Ryzen 7 7700.
> 
> Sorry if I don't have more details, I'm not a very tech savvy person, I'm not sure if there's a log I should be uploading or something.
> 
> Also setting clear_memory_page_state = true doesn't seem to change anything. I still have to hit F5 every time it goes weird.

Haven't reached that point yet. I'll experiment with changing options in the emulator itself.

**Comment by cerroverb** [comment]
> Hello, yes, it does help a bit. Beach screen shows up correctly on character select. Now it's this
> 
> ![Image](https://github.com/user-attachments/assets/5a740286-4395-4aab-806c-d4c7fd78351d)
> 
> And this
> 
> ![Image](https://github.com/user-attachments/assets/9c416bd7-5408-45a3-bb96-452ede0f4467)
> 
> ![Image](https://github.com/user-attachments/assets/8986114a-2a5c-41c7-ac3d-dc483b32152c)
> 
> ![Image](https://github.com/user-attachments/assets/bf378cc6-7ce8-4c0f-aef0-6c28c5d75f3e)

pretty much also what i'm experiencing with clear memory page state set as true. hope this game gets some fixes soon, as unlike NG2 and DOA4 it's not even available via backwards compatibility so this is pretty much the only way to play it outside of real hardware

**Comment by CrimsonFatalis** [comment]
Just curious, has the black texture under the characters been fixed?

**Comment by abudasdf-star** [comment]
> Just curious, has the black texture under the characters been fixed?

No, it's the same.

In older canary you can press f5 to fix it, the latest one it's not fixable

**Comment by whateverkeepsyouafloat-ctrl** [comment]
I'm having an issue with this game as well. 

<img width="1280" height="769" alt="Image" src="https://github.com/user-attachments/assets/d3a0acf4-822f-4e9b-9f66-dd7ff3e09596" />

If I try pression Options or Precious Memories, this error pops up and the game crashes entirely.

**Comment by arisupocket** [comment]
game boots on xenia edge on linux via proton with minor graphical issues at least on the menu. incredible achievement as it and DOA4 didn't even boot on normal XC running through proton let alone native linux XC. native xenia edge boots and makes it to menu and plays audio, but no graphics, just a black screen.

<img width="2559" height="1554" alt="Image" src="https://github.com/user-attachments/assets/c82dbe3f-35c0-47e4-90bc-9f135a85c367" />

**Comment by DavidHale34** [comment]
Tested on latest canary build [9132035](https://github.com/xenia-canary/xenia-canary-releases/releases/tag/9132035). Used same settings as DOA4. Game is generally playable and runs well with some graphic issues. Most glaring one is the black square on the ground that seem to follow the characters, my guess that's some kind of light source. It's absence makes the skin of the character look strange. Other minor transparency-related texture bugs that pop on occasion can be fixed with F5. Also, there is still a crash issue when entering options menu and there might be infinite loading and hanging on some tutorial screens (Marine Race, but can be skipped by reloading). 

The sound has one issue - too loud music, voices can be barely heard. Would try to fix by changing music or voices volume balance  but like I said above it's impossible to enter options. Changing the audio settings from DOA4 config to default ones didn't help and wasn't source of issue. Aside of that the music and all the other sound effects play well. 

All the shops, stages and minigames work properly (tested marine race, butt battle, casino, pool hopping), made it to day 3 without gameplay problem. Looks like can be finished completely till day 14. If those seemingly minor issues (black square, options screen) could be fixed in next release it'll be wonderful, as the game is nearly in playable state. Thanks for the work.

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/a30f9cd3-6ade-4caa-833f-2ab5e5643432" />
<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/0a7ee865-7938-42df-a618-6a62d5764b9c" />
<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/5c0662c3-c408-414b-bdfa-d33a0bfaba2a" />

**Comment by HylianSaint** [comment]
Using latest version of Canary and I am not experiencing any of the file IO crashing when going into Options or Precious Memories as shown in the images below. Haven't changed any settings in particular from initial install aside from the clear_memory_page_state = true for the visual bugs mentioned above. Not sure if this was fixed with a newer patch but just wanted to inform.

<img width="2562" height="1440" alt="Image" src="https://github.com/user-attachments/assets/5d70b9c4-3eb4-45d8-b9c0-32f66686f0be" />
<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/17f104e7-060e-40a4-9f06-f4e9fb30bb46" />

**Comment by DavidHale34** [comment]
Update on my previous message as I mistakenly used older version. Now tested on Dec 10 latest build. Used only clear_memory_page_state = true as above and draw_resolution_scale.

Options menu indeed have been fixed, no more hanging on tutorial screens either and most small texture bugs seem gone (or very rare) as well. 

However, the other problems still persist. Namely black square on the ground beneath the characters as well as darker ground illumination on some zones. Also, the ability to enter options didn't solve the music volume issue which stays at max no matter the setting, making voices hard to hear. This can be tested right in options menu. There is also a new bug that I didn't observe before - the water textures get broken and start to flicker on occasion at non default draw_resolution_scale (worth noting that DOA4 shares same problem now)

For the side note - in comparison to that older build I used the performance and stability seem to increase quite a bit, so even if those bugs haven't been addressed there been obviously many substantial changes "under the hood". Thanks for the work, again.

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/9e10dba0-0928-44d8-b75a-80092b530c31" />
Menu fixed, music volume slider broken.
<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/9f8e1eae-81dd-438b-9aeb-b4fedc5b0ed4" />
Black square problem persists
<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/06a5fffa-1059-44f4-89a3-f794771738e3" />
Occasional water reflection bug on draw_resolution_scale = 2 and above

**Comment by whateversh** [comment]
using the latest version (4fcb8e4 at the time of posting) and the audio slider issue has been fixed. you have to turn it down and then exit the menu for it to apply .

**Comment by CrimsonFatalis** [comment]
Glad it's still being worked on and fixed. I've missed playing a lot of 360
games, I honestly wish someone could re-compile it for better performance,
maybe 1 day :D

**Comment by Jay95Blu** [comment]
No noticeable graphics/menu/gameplay problems in canary version [8c98ef0](https://github.com/xenia-canary/xenia-canary/releases/tag/8c98ef0)! Still cannot disc-install, but otherwise seems stable.

**Comment by DavidHale34** [comment]
Yes, seems like indeed most issues have been resolved. Tested on the latest [ec5c875](https://github.com/xenia-canary/xenia-canary/releases/tag/ec5c875) build and I can confirm that the persisting black square and other lighting issues are finally fixed. Thanks to everyone who made this possible

<img width="3840" height="2160" alt="Image" src="https://github.com/user-attachments/assets/bc88e5ec-0d22-4f95-9396-f0be5f0f5d68" />
No more black square on the ground during scenes

<img width="3840" height="2160" alt="Image" src="https://github.com/user-attachments/assets/25ac5b12-6bb3-4824-afea-099483495d6d" />
